spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/gisdb
spring.datasource.username=gisuser
spring.datasource.password=gispassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
